[package]
name = "harper-tree-sitter"
version = "0.41.0"
edition = "2024"
description = "The language checker for developers."
license = "Apache-2.0"
repository = "https://github.com/automattic/harper"

[dependencies]
harper-core = { path = "../harper-core", version = "0.41.0" }
tree-sitter = "0.20.10"
