name: Build Web

on:
  push:
    branches: ["master", "web-prod"]
  pull_request:
    branches: ["master"]
  merge_group:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"
      - name: Retrieve version after install
        id: nodenv
        run: echo "node-version=$(node -v | sed 's/^v//')" >> $GITHUB_OUTPUT
      - uses: redhat-actions/buildah-build@719e3c40d8af9790c23eca13f7daa339f2867034 # v3.1.0
        with:
          image: web
          containerfiles: |
            Dockerfile
          build-args: |
            NODE_VERSION=${{ steps.nodenv.outputs.node-version }}-slim
          extra-args: |
            --ulimit nofile=65536:65536
