name: Chrome Plugin

on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  chrome-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"
      - name: Enable Corepack
        run: corepack enable
      - uses: cargo-bins/cargo-binstall@b874e25ea559687bec77e281e9b271aa1367b624 # main
      - name: Install `wasm-pack`
        run: cargo binstall wasm-pack --force --no-confirm
      - name: Build Chrome Plugin
        run: just build-chrome-plugin
      - name: Build Firefox Plugin
        run: just build-firefox-plugin
      - name: Upload Chrome extension
        uses: actions/upload-artifact@v7
        with:
          name: harper-chrome-plugin.zip
          path: "packages/chrome-plugin/package/harper-chrome-plugin.zip"
      - name: Upload Firefox extension
        uses: actions/upload-artifact@v7
        with:
          name: harper-firefox-plugin.zip
          path: "packages/chrome-plugin/package/harper-firefox-plugin.zip"
      - name: Release artifacts
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: "packages/chrome-plugin/package/*.zip"
          allowUpdates: true
          draft: true
