name: Harper Desktop for Windows

on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  desktop-windows:
    name: just build-desktop-windows
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"
      - name: Enable Corepack
        run: corepack enable
      - name: Install Tauri and cross-compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libwebkit2gtk-4.1-dev \
            libxdo-dev \
            llvm \
            nsis
      - name: Verify Windows build tools
        run: command -v clang-cl llvm-lib makensis
      - name: Rust Cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          cache-bin: "true"
          key: build-desktop-windows
      - uses: cargo-bins/cargo-binstall@b874e25ea559687bec77e281e9b271aa1367b624 # main
      - name: Install `wasm-pack`
        run: cargo binstall wasm-pack --force --no-confirm
      - name: Install `cargo-xwin`
        run: cargo binstall cargo-xwin --force --no-confirm
      - name: Install `tauri-cli`
        run: cargo binstall tauri-cli --force --no-confirm
      - name: Build Harper Desktop for Windows
        run: just build-desktop-windows
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: harper-desktop-windows-x64
          path: target/x86_64-pc-windows-msvc/release/bundle/nsis/*
          if-no-files-found: error
      - name: Release artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          artifacts: target/x86_64-pc-windows-msvc/release/bundle/nsis/*
          allowUpdates: true
          draft: true
