name: Release WordPress Plugin 

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
      - name: Enable Corepack
        run: corepack enable
      - name: Install `pandoc`
        run: sudo apt-get update && sudo apt-get install pandoc -y
      - uses: cargo-bins/cargo-binstall@main
      - name: Install `wasm-pack`
        run: cargo binstall wasm-pack --force --no-confirm
      - name: Build
        run: just build-wp 
      - name: Upload extension
        uses: actions/upload-artifact@v4
        with:
          name: harper.zip
          path: "packages/wordpress-plugin/harper.zip"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "packages/wordpress-plugin/harper.zip"
          allowUpdates: true
          draft: true
